<% require "dotenv"; Dotenv.load(".env") %>
# config/deploy.yml
service: whereswaldo

image: danscorpan/whereswaldo

servers:
  web:
    hosts:
      - 62.171.183.69 # The IP of the staging server from Hetzner

registry:
  username: 
  - KAMAL_USERNAME
  password:
  - KAMAL_REGISTRY_PASSWORD

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true # Let Rails serve static files (since no external proxy in production)
    RAILS_LOG_TO_STDOUT: true # Log to STDOUT for Docker logging
  secret:
    - RAILS_MASTER_KEY # Rails master key (provide in .kamal/secrets)
    - DB_URL # Database connection string (provided per env in secrets)
    - DB_HOST
    - DB_USER
    - DB_PASSWORD
    - DB_PORT


proxy:
  ssl: false
  host: 62.171.183.69
  app_port: 3000

builder:
  arch: amd64
  args:
    RAILS_ENV: production
  secrets:
    - KAMAL_USERNAME
    - KAMAL_REGISTRY_PASSWORD
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE

accessories:
  postgres:
    image: postgres:17 # Use the correct version for your app
    host: DB_HOST
    port: DB_PORT
    env:
      clear:
        DB_USER: whereswaldo
        DB: whereswaldo_production
      secret:
        - DB_PASSWORD
        - DB_USER
    files:
      - config/init.sql:/docker-entrypoint-initdb.d/setup.sql    
    directories:
      - data:/var/lib/postgresql/data # Persist db data on host (named volume "data")
ssh:
  user: jaws
